# Generated by Django 5.1.1 on 2024-09-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_employee_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
