# Generated by Django 5.1.1 on 2024-09-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_restaurantvote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="menu",
        ),
        migrations.DeleteModel(
            name="RestaurantVote",
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
