# Generated by Django 5.1.1 on 2024-09-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
