# Generated by Django 5.1.1 on 2024-09-12 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="voted_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
