# Generated by Django 5.1.1 on 2024-09-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0010_alter_vote_voted_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="opening_hours",
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.TextField(),
        ),
    ]
