# Generated by Django 5.1.1 on 2024-09-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0013_alter_menu_points"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="points",
            new_name="votes",
        ),
        migrations.AlterField(
            model_name="vote",
            name="points",
            field=models.IntegerField(default=1),
        ),
    ]
